### ISSUE TITLE
是否可以支持一下OC

### ISSUE THREAD

**Issue by hardyZhi** [623637646/ImpressionKit#1]
是否可以支持一下OC

**Comment by 623637646** [comment]
目前没有计划支持OC，不过业务方可以很方便的自己封装一下。比如创建一个 ImpressionKitWrapper.swift，里面的接口都是暴露给OC的。 OC代码可以方便调用 ImpressionKitWrapper.swift，ImpressionKitWrapper.swift 负责调用 ImpressionKit的API。

**Comment by Dwarven** [comment]
写了一个 OC 版本的，顺带在 OC 版本上修了点bug，可以试试 @hardyZhi 
https://github.com/Dwarven/ImpressionKit-OC

**Comment by 623637646** [comment]
hi @Dwarven , 刚看了下你写的OC版本的ImpressionKit。 代码质量很高。赞
请问下你说的修复点bug，是指 我的 ImpressionKit 有bug么？ 可以讲讲是什么bug么？ 如果需要，我去修复它。
