### ISSUE TITLE
ImpressionGroup().redetectOptions  no work

### ISSUE THREAD

**Issue by liusr** [623637646/ImpressionKit#11]
var impressionGroup: ImpressionGroup = {
        let impression = ImpressionGroup.init {(_, index: IndexPath, view, state) in
        }
impression.redetectOptions = [.leftScreen]//no work
        UIView.redetectOptions = [.leftScreen]//usefull
        return impression
    }()

**Comment by 623637646** [comment]
Thanks for your contribution. It's fixed by https://github.com/623637646/ImpressionKit/commit/5bc79cac00bb44bf576a0b8132519e0241383907
You may use the newest version `3.7.3` to handle it.

**Comment by liusr** [comment]
Thank you
