### ISSUE TITLE
AreaRatio Calculation problem with SuperView

### ISSUE THREAD

**Issue by PangMo5** [623637646/ImpressionKit#2]
First, thank you for making a nice kit.

For example, if the frame of ScrollView in the example app is `CGRect(x: 0, y: self.view.frame.height / 2, width: self.view.frame.width, height: self.view.frame.height / 2)`,

AreaRatio doesn't seem to be calculated normally.

Thanks.

https://user-images.githubusercontent.com/16532526/123039840-c5ad0700-d42d-11eb-95b8-e1257d847678.mp4

**Comment by PangMo5** [comment]
Added a related example to the forked branch.
https://github.com/PangMo5/ImpressionKit/tree/PangMo5/ViewHeightRatio

**Comment by 623637646** [comment]
Thank you so much @PangMo5 . Fixed.  Let me know if you face any issues.
