### ISSUE TITLE
[Feature Request] SwiftUI support

### ISSUE THREAD

**Issue by PangMo5** [623637646/ImpressionKit#5]
Thank you for the nice library.

Can you also support `View` on `SwiftUI`?

**Comment by 623637646** [comment]
Thanks, Good point @PangMo5 , But sorry, I am not familiar with `SwiftUI` and I am not available recently. Could you please help to implement this feature and take a pull request if possible?

**Comment by PangMo5** [comment]
> Thanks, Good point @PangMo5 , But sorry, I am not familiar with `SwiftUI` and I am not available recently. Could you please help to implement this feature and take a pull request if possible?

Yes, I recently tried to make ImpressionKit for SwiftUI using `GeometryReader` and `CoordinateSpace`.
But it didn't go as well as I thought. :(
If I succeed, I will post PR. XD

Could you explain the code that measures areaRatio?

**Comment by 623637646** [comment]
> Yes, I recently tried to make ImpressionKit for SwiftUI using GeometryReader and CoordinateSpace.

Personally, I think you can try this: 
1. Create a custom view named `ImpressionView`, It's extended from `UIView`.  
2. Make `ImpressionView` support impression feature by the `ImpressionKit`.
3. Export it to SwiftUI. The following doc is how to use custom view in SwiftUI.

https://www.vadimbulavin.com/using-uikit-uiviewcontroller-and-uiview-in-swiftui/
<img width="883" alt="Screenshot 2021-07-22 at 4 41 30 PM" src="https://user-images.githubusercontent.com/5275802/126611927-17445c02-6faa-4633-9ff0-bee4dd2a1bee.png">

Hope it's helpful.

**Comment by 623637646** [comment]
Done, Thanks!.

**Comment by 623637646** [comment]
Hi @PangMo5 , I just had a try. 
Seems `UIView.redetectOptions = []`  doesn't work fine. 
It always redetects when left screen just like set `UIView.redetectOptions = [.leftScreen] ` (expected no re-detection).

**Comment by PangMo5** [comment]
Hmm.. I'll check it

**Comment by PangMo5** [comment]
@623637646 

All redirectOptions that can be set in the example app appear to be functioning normally.

Please check the abnormal works you mentioned in UISrollView, UICollectionView, and UITableView.

It could be redetectOptions's own problem.

**Comment by 623637646** [comment]
I am using the SwiftUI demo. You can see the issue in the video. The views always redetect when left screen even though I set `UIView.redetectOptions = []`. @PangMo5 

https://user-images.githubusercontent.com/5275802/126638170-5596474b-c701-41d9-8913-d894ab0caf3a.mov

**Comment by PangMo5** [comment]
Oh, I'm sorry.
I understand what you mean.
We need something similar to ImpressionGroup to do related work.

I was confused with the Impression method that I use personally 🤯 

I'll work and upload it.

**Comment by PangMo5** [comment]
SwiftUI structure is different from UIKit.
I can't think of anything to replace ImpressionGroup right now :(

View of SwiftUI cannot be used as parameters for functions.
like ImpressionGroup's `public func bind(view: UIView, index: IndexType)`

I'm sorry for can't help you.

Please let me know if you have any other ideas to manage the ImpressionStates. I'll think about it.

For your information, in a personal project that created by reference to this project,
Each View(State) has an adID(Hashable) and checks it for redundancy in Singleton Object.

Anyway, I'll look for more when I have time.

**Comment by 623637646** [comment]
Hi, It's fine. no worry about this.

> View of SwiftUI cannot be used as parameters for functions. like ImpressionGroup's `public func bind(view: UIView, index: IndexType)`

Is it possible to do the `public func bind(view: UIView, index: IndexType)` in `ImpressionView`'s `func makeUIView(context: UIViewRepresentableContext<ImpressionView>) -> UIView` ? 
In other words:

1. Create a new node named `ImpressionGroupView`,
2. `ImpressionGroupView` contains the instance of `ImpressionGroup`.
3.  Get the instance of `ImpressionGroup` and the `index` from `ImpressionGroupView` in `ImpressionView`. (Maybe this is not possible)
4. Then we can set up the group impression.

I never used SwiftUI, Just a rough idea. 

> Anyway, I'll look for more when I have time.

Take your time. Thanks again for your effort.

**Comment by 623637646** [comment]
Very good job @PangMo5 . I will take a little bit change and release the formal version later.

**Comment by 623637646** [comment]
I had some small changes https://github.com/623637646/ImpressionKit/commit/3367c2ebfffcf6dbd341f64afe12c2004e0bcce6
and released the 3.2.0 version.  Thank you! @PangMo5

**Comment by PangMo5** [comment]
Thank you for the nice library! XD @623637646
