### ISSUE TITLE
Redetection doesn't work properly when .didEnterBackground is selected as Redetection Option with CollectionView reusable views

### ISSUE THREAD

**Issue by lionserdar** [623637646/ImpressionKit#9]
If user selects `.didEnterBackground` as redetection Option and puts the application background then in foreground ImpressionKit doesn't detect impressions properly. 

Here's the steps to reproduce
1. Launch App
2. Select `Redetect When didEnterBackground` from Settings
3. Select `UICollectionView (reused views)` from Demos 
4. Slowly scroll to the bottom of the `CollectionView`. Make sure all views are `impressed` (marked with green color).
5. Once all cells are impressed (marked with green color) scroll to the top of the `CollectionView`  then scroll to the bottom of the `CollectionView`
6. Put application to `background`
7. Bring the application to the `foreground`

Result: Application gets into `foreground state` however all cells are already marked with green color -impressed.  (Sometimes - cells stays on white color or impression only works partially for some cells). Also logs doesn't show any indication of redetection.
 
Expected behaviour: Impression should be redetected - Cell colors should be White- Red-Green.

**Comment by 623637646** [comment]
Fixed on 3.7.0. Thank you for your report. @lionserdar
